name: Test

on: [push, pull_request]

jobs:
  build_and_test_serenity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Ubuntu dependencies"
        
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm

      - name: Run tests
        run: cd ${{ github.workspace }} && make test
